import type { Brand, BrandProfile } from "@/lib/types";

export const brandProfiles: Record<Brand, BrandProfile> = {
  "nadinepierre.com": {
    brand: "nadinepierre.com",
    displayName: "Nadine Pierre",
    positioning: "Founder authority and entrepreneur profile for media visibility and leadership credibility.",
    voice: "Founder-led, precise, warm, credible, reflective, media-ready.",
    authorityPillars: ["founder authority", "entrepreneur profile", "media visibility", "leadership voice"],
    coreTopics: ["founder authority", "entrepreneurship", "media visibility", "leadership voice", "decision-making"],
    audience: "Founders, operators, partners, podcast hosts, and media contacts.",
    ctaOptions: ["Visit nadinepierre.com", "Explore Nadine's work", "Invite Nadine to speak"],
    defaultCadence: ["3 founder authority posts weekly", "1 podcast visibility opportunity weekly"],
  },
  "leadwithnadine.com": {
    brand: "leadwithnadine.com",
    displayName: "Lead With Nadine",
    positioning: "Leadership communication guidance for difficult conversations and authority under pressure.",
    voice: "Practical, psychologically intelligent, direct, grounded, empowering.",
    authorityPillars: [
      "leadership communication",
      "difficult conversations",
      "overexplaining",
      "women stepping into authority",
      "frontline leadership",
    ],
    coreTopics: ["leadership communication", "difficult conversations", "overexplaining", "frontline leadership", "authority"],
    audience: "Women leaders, managers, and emerging frontline leaders.",
    ctaOptions: ["Visit leadwithnadine.com", "Use the clarity tool", "Practice the conversation before it happens"],
    defaultCadence: ["1 LinkedIn post daily", "1 TikTok or Instagram caption daily", "1 authority article weekly"],
  },
  "getstratiq.co": {
    brand: "getstratiq.co",
    displayName: "GETSTRATIQ",
    positioning: "Strategic reasoning and AI-assisted decision clarity for executives and operators.",
    voice: "Analytical, executive, concise, risk-aware, decision-oriented.",
    authorityPillars: ["strategic reasoning", "executive thinking", "AI analysis", "risk thinking", "decision clarity"],
    coreTopics: ["strategic reasoning", "AI analysis", "risk thinking", "decision clarity", "executive decisions"],
    audience: "Executives, founders, strategists, and teams using AI for better decisions.",
    ctaOptions: ["Visit getstratiq.co", "Improve decision clarity", "Use AI for sharper analysis"],
    defaultCadence: ["3 strategic thinking posts weekly", "1 AI-search article weekly"],
  },
  "getcontentos.co": {
    brand: "getcontentos.co",
    displayName: "GetContentOS",
    positioning: "AI content system for creators, professionals, and small businesses.",
    voice: "Systems-minded, practical, observant, direct, non-generic, and grounded in real content operations.",
    authorityPillars: [
      "content strategy",
      "authority building",
      "AI-assisted content creation",
      "repurposing",
      "social media systems",
      "creator workflows",
      "marketing consistency",
    ],
    coreTopics: [
      "content strategy",
      "authority building",
      "AI-assisted content creation",
      "repurposing",
      "social media systems",
      "creator workflows",
      "marketing consistency",
    ],
    audience: "Creators, professionals, consultants, founders, coaches, and small business owners.",
    ctaOptions: [
      "GetContentOS.co",
      "Try the content system",
      "Create better content faster",
      "Build authority without generic posting",
    ],
    defaultCadence: ["3 creator growth posts weekly", "1 repurposing article weekly"],
  },
  "calmauthority.co": {
    brand: "calmauthority.co",
    displayName: "Calm Authority",
    positioning: "Workplace scripts and calm communication templates for difficult conversations.",
    voice: "Calm, practical, script-driven, compassionate, firm.",
    authorityPillars: ["workplace scripts", "difficult conversations", "communication templates", "calm authority"],
    coreTopics: ["workplace scripts", "difficult conversations", "communication templates", "calm authority", "emotional control"],
    audience: "Professionals and leaders who need clearer workplace conversations.",
    ctaOptions: ["Visit calmauthority.co", "Use a calmer script", "Prepare the conversation before it escalates"],
    defaultCadence: ["3 communication posts weekly", "1 script or template post weekly"],
  },
};

export const brands = Object.keys(brandProfiles) as Brand[];
